---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-sample
  name: webapp-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-sample
  template:
    metadata:
      labels:
        app: webapp-sample
    spec:
      containers:
        - name: webapp-sample
          image: gcr.io/arctiq-mission-302500/webapp-sample
          ports:
            - containerPort: 8080
