apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:882d3231d4c099ebf6632c7d9cdbd4596fa767f83ba46d8260a9689dbe653f41
  name: gcr.io/arctiq-mission-302500/webapp-sample
