apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:38296abb6812d2eebe666ee1e4dfa6d6f8227c4e69871c4b77dfc67423bdaba1
  name: gcr.io/arctiq-mission-302500/webapp-sample
