apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:fc82ee6ec2017fcb0434566f40d785cd2872dc18716f34ce2319d4b8d1078e52
  name: gcr.io/arctiq-mission-302500/webapp-sample
