apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:97f22705c09b85b68e9f36aa8a36643673c8497ca009dc4a8588a6bbd69e11f1
  name: gcr.io/arctiq-mission-302500/webapp-sample
