apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:c306616bd0524c6ad89f2bbb1edbc791c052867be9a567b2bc4b1e5a6ed3e482
  name: gcr.io/arctiq-mission-302500/webapp-sample
