apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:861f0613596dce82b56db279d05d9751caa2afa851212aa5fca7a0d4c71eca45
  name: gcr.io/arctiq-mission-302500/webapp-sample
