apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:24a345e94c544865064588161370ad9f3d99ef5f6c917fde7af120d12494629b
  name: gcr.io/arctiq-mission-302500/webapp-sample
