apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:09eeafbdcc3f0704a8c4600e1aea6a3856acbc701bf26682e63c432e3ed4f0cb
  name: gcr.io/arctiq-mission-302500/webapp-sample
