apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:aa12b7fd82c82c69fe97f4f4d51674817c9db9893cc8ee2d5a57638f7a48e0bc
  name: gcr.io/arctiq-mission-302500/webapp-sample
