apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:07aef404763a10afdde5bc606ccbbaae63c54165a69ad5a464272f48b5e3a513
  name: gcr.io/arctiq-mission-302500/webapp-sample
