apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:353d7e2af7a025cba632deab2245a0bec8a9f21acf8f44fb168a869e21784a96
  name: gcr.io/arctiq-mission-302500/webapp-sample
