apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:13a5380205ed26d3186fbdd343d2277e8f16000d4b91590ee7e8fc7d92d8b2ae
  name: gcr.io/arctiq-mission-302500/webapp-sample
