apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:f968e13dbd3a76c7dfba9d5f21f7cf5bfc211bdc6441fdc6b5872ef93b063261
  name: gcr.io/arctiq-mission-302500/webapp-sample
