apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:77d1d5cfee88577928ab40870246a7721ded873acc572ab60d41ca67eb130e24
  name: gcr.io/arctiq-mission-302500/webapp-sample
