apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:3e0d1f18d76eda0016870fced2669a5823d0ccc418139b0e9007b241bbbd0bb4
  name: gcr.io/arctiq-mission-302500/webapp-sample
