apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:204d165ea4d8344179b91661f578c615dbf81429faac2bb3273605c71ced7b7c
  name: gcr.io/arctiq-mission-302500/webapp-sample
