apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:8b9562e132fd32486eeba430e0c2c16342bfd31cd79bd4daff89bab38750d825
  name: gcr.io/arctiq-mission-302500/webapp-sample
