apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:c78ed37622f284650fa746cff66bf1dfa7a31cb918e9a6656b156e3d2ea847de
  name: gcr.io/arctiq-mission-302500/webapp-sample
