apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:a3123b5802d1894803db0c4d178c673c616cc57e783a797a3bf7240e46f2933c
  name: gcr.io/arctiq-mission-302500/webapp-sample
