apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:119e5a30240819059ebee1318f49993ef82de83e0e20bbb5d337a19dc3fcded3
  name: gcr.io/arctiq-mission-302500/webapp-sample
