apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:19c68f1de987fcb2c9234d4bf1fc0fb58493d3b33e350fc8be8118f2a7901d15
  name: gcr.io/arctiq-mission-302500/webapp-sample
