---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-sample
  name: webapp-sample
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-sample
  type: LoadBalancer
