envs:
- cluster_name: mission-cluster
  compute:
    zone: northamerica-northeast1-b
  creation_time: "2021-01-24T20:40:37Z"
  last_update_time: "2021-01-24T20:40:37Z"
  name: dev
  namespace: webapp-sample-dev
  project: arctiq-mission-302500
